{
 "title": "Hoshiguma: Devices",
 "tags": [ "Hoshiguma" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Telemetry Bridge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Revision",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"telemetry_module_git_revision\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Boot Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"telemetry_module_boot_reason\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"telemetry_module_uptime\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Revision",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"orchestrator_git_revision\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Boot Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"orchestrator_boot_reason\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"orchestrator_uptime\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    }
   ]
  },
  {
   "title": "Rear Sensor Board",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Revision",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"rear_sensor_board_git_revision\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Boot Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"rear_sensor_board_boot_reason\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"rear_sensor_board_uptime\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    }
   ]
  },
  {
   "title": "HMI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Revision",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"hmi_git_revision\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Boot Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"hmi_boot_reason\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"hmi_uptime\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    }
   ]
  },
  {
   "title": "Cooler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Revision",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"cooler_git_revision\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Boot Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"cooler_boot_reason\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"cooler_uptime\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    }
   ]
  }
 ]
}