{
 "title": "Hoshiguma: Overview",
 "tags": [ "Hoshiguma" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Access Control",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"access_control_state\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_power\")\n  |> keep(columns: [\"_time\", \"_value\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"machine_power\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Machine Operation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"safety.lockout\")\n  |> keep(columns: [\"_time\", \"_value\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"interlock\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Run Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 3d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.machine_run\")\n  |> keep(columns: [\"_time\", \"_value\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"machine_run\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Coolant Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.temperature\")\n  |> filter(fn: (r) => r[\"source\"] == \"cooler\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /reservoir_*/)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"sensor\",\n  \"value\"\nFROM (\n  SELECT\n    \"time\",\n    \"sensor\",\n    \"value\",\n    ROW_NUMBER() OVER (\n      PARTITION BY \"sensor\"\n      ORDER BY \"time\" DESC\n    ) AS \"row_num\"\n  FROM \"temperature\"\n  WHERE \"time\" >= $__timeFrom\n    AND \"time\" <= $__timeTo\n) ranked\nWHERE \"row_num\" = 1 AND \"sensor\" IN ('CoolantFlowAtTube', 'CoolantReturnAtTube', 'CoolantReservoir')\nORDER BY \"sensor\""
    }
   ]
  },
  {
   "title": "Coolant Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.coolant_flow\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"coolant_flow_rate\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"coolant_return_rate\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Fume Extraction Airflow Suction",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.extraction_airflow_suction\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"extraction_airflow_suction\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "iox",
     "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"safety.monitors\")\n  |> keep(columns: [\"_value\", \"_field\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"monitor\",\n  \"severity\",\nFROM (\n  SELECT\n    \"time\",\n    \"monitor\",\n    \"severity\",\n    ROW_NUMBER() OVER (\n      PARTITION BY \"monitor\"\n      ORDER BY \"time\" DESC\n    ) AS \"row_num\"\n  FROM \"monitor\"\n  WHERE \"time\" >= $__timeFrom\n    AND \"time\" <= $__timeTo\n) ranked\nWHERE \"row_num\" = 1\n  AND \"severity\" != 'normal'\nORDER BY \"monitor\""
    }
   ]
  },
  {
   "title": "Fume Extraction Fan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"control.fume_extraction_fan\")\n  |> keep(columns: [\"_time\", \"_value\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"fume_extraction_fan\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Cooler Compressor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cooling.demand\")\n  |> keep(columns: [\"_time\", \"_value\"])",
     "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"compressor\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.temperature\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"source\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
       "rawSql": "SELECT\n  \"time\",\n  \"sensor\",\n  \"value\",\nFROM \"temperature\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    },
    {
     "title": "Monitors",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "dataset": "iox",
       "query": "import \"date\"\n\nfrom(bucket: \"Hoshiguma\")\n  |> range(start: date.sub(d: 1d, from: v.timeRangeStart), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"safety.monitors\")\n  |> keep(columns: [\"_value\", \"_field\"])",
       "rawSql": "SELECT\n  \"time\",\n  \"monitor\",\n  \"severity\",\nFROM \"monitor\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\" DESC"
      }
     ]
    },
    {
     "title": "Coolant Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.coolant_flow\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"coolant_flow_rate\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      },
      {
       "dataset": "iox",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"coolant_return_rate\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    },
    {
     "title": "Fume Extraction Airflow Suction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "pressurepa" } },
     "targets": [
      {
       "dataset": "iox",
       "query": "from(bucket: \"Hoshiguma\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"observation.extraction_airflow_suction\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
       "rawSql": "SELECT\n  \"time\",\n  \"value\",\nFROM \"extraction_airflow_suction\"\nWHERE \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nORDER BY \"time\""
      }
     ]
    }
   ]
  }
 ]
}