keys:
  - &dannixon-sk-yellow age1yubikey1qgxj47xg2sxwv95w0zhlqw7ay4qsdltjgura29wd57kmx5hjfdaxxxla29h
  - &dannixon-sk-blue age1yubikey1q0ukp0umwpvky9eamjym59mh42p5nz5q02zvx5mhfy57t6xmnzzm5zvaugq
  - &dannixon-sk-green age1yubikey1qvm5j08damled24uvgaeveg0znt9f8sr8e8d5e4sdh9j75g9z8wnq6s5lwg
  - &dannixon-sk-red age1yubikey1q236gnfv88v7ln4drft9y7swllwc5la5m9dut57ck8e9kcs0e32zqnqfg8l

creation_rules:
  - path_regex: '.*.secrets.yml'
    key_groups:
      - age:
          - *dannixon-sk-yellow
          - *dannixon-sk-blue
          - *dannixon-sk-green
          - *dannixon-sk-red
