{
 "title": "Creative Crawl Christmas 2025 box",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Talisman Triggers",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"Creative Crawl 2025\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"talisman_trigger_count\")\n  |> keep(columns: [\"_time\", \"_value\", \"talisman\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Stories Played",
   "type": "table",
   "gridPos": { "h": 30, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"Creative Crawl 2025\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"story_select_count\")\n  |> keep(columns: [\"_value\", \"story\"])\n  |> group(columns: [\"story\"])\n  |> count(column: \"_value\")\n  |> rename(columns: {_value: \"count\"}) // Optionally rename for clarity\n  |> keep(columns: [\"story\", \"count\"]) // Only show story and count\n  |> group()\n  |> sort(columns: [\"count\"], desc: true)"
    }
   ]
  },
  {
   "title": "Stories Played",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Creative Crawl 2025\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"story_select_count\")\n  |> keep(columns: [\"_time\", \"_value\", \"story\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Door",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"Creative Crawl 2025\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"door_opened\")\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  { "title": "Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"Creative Crawl 2025\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_ms\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network Configuration Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"Creative Crawl 2025\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_config_age_ms\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}