{
 "title": "Kubernetes Overview",
 "tags": [ "infrastructure" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Longhorn Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_volume_capacity_bytes{}",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Longhorn Volume Actual Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "longhorn_volume_actual_size_bytes{}",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Longhorn Disks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "longhorn_disk_capacity_bytes{}", "legendFormat": "{{ disk }} capacity" },
    { "expr": "longhorn_disk_usage_bytes{}", "legendFormat": "{{ disk }} usage" }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{}[$__rate_interval])",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=~\".+\"}",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container=~\".+\"}",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ container }}"
    }
   ]
  }
 ]
}