logs:
  general:
    level: INFO

additionalArguments:
  - --entrypoints.web.http.redirections.entrypoint.to=:443
  - --entrypoints.web.http.redirections.entrypoint.scheme=https
  - --entrypoints.web.http.redirections.entrypoint.permanent=true

ports:
  traefik:
    port: 9000
    protocol: TCP
    expose:
      default: false
  web:
    port: 8000
    protocol: TCP
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 8443
    protocol: TCP
    expose:
      default: true
    exposedPort: 443
  mqtt:
    port: 1883
    protocol: TCP
    expose:
      default: true
    exposedPort: 1883
