---
cluster:
  name: makerspace-on-prem

global:
  scrapeInterval: 15s

destinations:
  cloud-prometheus:
    type: prometheus
    url: https://prometheus.dan-nixon.com/write
    auth:
      type: basic
      username: makerspace-k8s
      password: ref+sops://src/secrets.yml#/prometheus_password

  grafana-cloud-loki:
    type: loki
    url: https://logs-prod-035.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: '1482225'
      password: ref+sops://src/secrets.yml#/grafana_cloud_token

collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset

  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset

  alloy-singleton:
    presets:
      - singleton

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics
  annotations:
    scrape: prometheus.io/scrape
    metricsScheme: prometheus.io/scheme
    metricsPath: prometheus.io/path
    metricsPortNumber: prometheus.io/port

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
    metricsTuning:
      useIntegrationAllowList: true

clusterMetrics:
  enabled: true
  collector: alloy-metrics

clusterEvents:
  enabled: true
  collector: alloy-singleton

nodeLogs:
  enabled: true
  collector: alloy-logs

podLogsViaLoki:
  enabled: true
  collector: alloy-logs

telemetryServices:
  node-exporter:
    deploy: true
  kube-state-metrics:
    deploy: true
