---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: creative-crawl
data:
  telegraf.conf: |
    [agent]
      debug = true
      quiet = false

    [[outputs.influxdb_v2]]
      bucket = "Creative Crawl 2025"
      organization = "Maker Space"
      token = "ref+sops://src/secrets.yml#/influx_token"
      urls = ["http://influxdb.influxdb.svc.cluster.local.:8086"]

    [[inputs.http_listener_v2]]
      data_format = "influx"
      service_address = "tcp://:8080"
      paths = ["/"]
      methods = ["POST"]
      http_success_code = 204
      basic_username = "creative-crawl-2025"
      basic_password = "ref+sops://src/secrets.yml#/http_password"
