#
# This is a generated file!
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: environment-sensors
data:
  telegraf.conf: |
    [agent]
      debug = true
      quiet = false

    [[outputs.influxdb_v2]]
      bucket = "Environment"
      organization = "Maker Space"
      token = "ref+sops://src/secrets.yml#/influx_token"
      urls = ["http://influxdb.influxdb.svc.cluster.local.:8086"]

    [[inputs.prometheus]]
      interval = "30s"
      urls = ["http://192.168.8.204/metrics"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: environment-sensors
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
        app.kubernetes.io/instance: telegraf
    spec:
      containers:
        - name: telegraf
          image: "docker.io/library/telegraf:1.35-alpine"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf
      volumes:
        - name: config
          configMap:
            name: telegraf
---
apiVersion: v1
kind: Namespace
metadata:
  name: environment-sensors
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dashboard-temperatures
  namespace: environment-sensors
  labels:
    grafana_dashboard: "1"
data:
  environment-sensors-temperature.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 1,
      "id": 12,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "P951FEA4DE68E13C5"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green"
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "celsius"
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "gauge board_temperature"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Board"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "gauge temperature_1"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Sensor 1"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "gauge temperature_2"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Sensor 2"
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 15,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "legend": {
              "calcs": [
                "mean",
                "max",
                "lastNotNull"
              ],
              "displayMode": "table",
              "placement": "right",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "multi",
              "sort": "none"
            }
          },
          "pluginVersion": "11.6.0",
          "targets": [
            {
              "datasource": {
                "type": "influxdb",
                "uid": "P951FEA4DE68E13C5"
              },
              "query": "from(bucket: \"Environment\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"esphome_sensor_value\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
              "refId": "A"
            }
          ],
          "title": "Comms. Room Temperatures",
          "type": "timeseries"
        }
      ],
      "preload": false,
      "refresh": "1m",
      "schemaVersion": 41,
      "tags": [
        "Environment"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-24h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Environment: Temperatures",
      "uid": "aejqxf21cfqioa",
      "version": 3
    }
