#
# This is a generated file!
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: influxdb
spec:
  secretName: tls-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - influxdb.makerspace.dan-nixon.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: influxdb
  labels:
    app.kubernetes.io/name: influxdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
    spec:
      containers:
        - name: influxdb
          image: docker.io/library/influxdb:2.7.11
          ports:
            - name: influxdb-http
              containerPort: 8086
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-data
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  selector:
    app.kubernetes.io/name: influxdb
  ports:
    - port: 8086
      protocol: TCP
      targetPort: influxdb-http
---
kind: Secret
apiVersion: v1
metadata:
  name: grafana-datasource-influxdb
  namespace: influxdb
  labels:
    grafana_datasource: "1"
stringData:
  influxdb.yaml: |
    apiVersion: 1

    datasources:
      - name: InfluxDB
        type: influxdb
        url: http://influxdb.influxdb.svc.cluster.local.:8086
        jsonData:
          version: Flux
          organization: Maker Space
          defaultBucket: Default
          tlsSkipVerify: true
        secureJsonData:
          token: ref+sops://src/secrets.yml#/grafana_token
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http
  namespace: influxdb
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`influxdb.makerspace.dan-nixon.com`)
      services:
        - Kind: Service
          name: influxdb
          port: 8086
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
