---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasource-loki
  namespace: monitoring-logs
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        url: http://loki.monitoring-logs.svc.cluster.local.:3100
