---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: environment-sensors
data:
  telegraf.conf: |
    [agent]
      debug = true
      quiet = false

    [[outputs.influxdb_v2]]
      bucket = "Environment"
      organization = "Maker Space"
      token = "ref+sops://src/secrets.yml#/influx_token"
      urls = ["http://influxdb.influxdb.svc.cluster.local.:8086"]

    [[inputs.prometheus]]
      interval = "30s"
      urls = [
        "http://192.168.8.204/metrics",
        "http://192.168.8.196/metrics",
        "http://192.168.8.79/metrics",
      ]
