---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasource-prometheus
  namespace: monitoring-metrics
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring-metrics.svc.cluster.local.
