#
# This is a generated file!
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: hoshiguma
spec:
  secretName: tls-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - hoshiguma-telemetry-feed.makerspace.dan-nixon.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: hoshiguma
data:
  telegraf.conf: |
    [agent]
      debug = true
      quiet = false

    [[outputs.influxdb_v2]]
      bucket = "Hoshiguma"
      organization = "Maker Space"
      token = "ref+sops://src/secrets.yml#/influx_token"
      urls = ["http://influxdb.influxdb.svc.cluster.local.:8086"]

    [[inputs.http_listener_v2]]
      data_format = "influx"
      service_address = "tcp://:8080"
      paths = ["/"]
      methods = ["POST"]
      http_success_code = 204
      basic_username = "hoshiguma"
      basic_password = "ref+sops://src/secrets.yml#/http_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: hoshiguma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
        app.kubernetes.io/instance: telegraf
    spec:
      containers:
        - name: telegraf
          image: "docker.io/library/telegraf:1.34-alpine"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf
      volumes:
        - name: config
          configMap:
            name: telegraf

---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-telemetry-feed
  namespace: hoshiguma
spec:
  selector:
    app.kubernetes.io/name: telegraf
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: telemetry-feed
  namespace: hoshiguma
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`hoshiguma-telemetry-feed.makerspace.dan-nixon.com`)
      services:
        - Kind: Service
          name: telegraf-telemetry-feed
          port: 8080
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: hoshiguma
