---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Check code formatting
        shell: devenv shell bash -- -e {0}
        run: treefmt --fail-on-change


  render-manifests:
    name: Render Manifests
    runs-on: ubuntu-latest
    needs:
      - formatting

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Render all manifests
        shell: devenv shell bash -- -e {0}
        run: |
          cd ./apps
          ./render.sh

      - name: Check committed manifests are up to date
        shell: devenv shell bash -- -e {0}
        run: git diff --exit-code
