---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Check code formatting
        run: nix develop --command treefmt --fail-on-change


  render-manifests:
    name: Render Manifests
    runs-on: ubuntu-latest
    needs:
      - formatting

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Render all manifests
        run: |
          cd ./apps
          nix develop --command ./render.sh

      - name: Check committed manifests are up to date
        run: git diff --exit-code
